name: DigiCert test

on: [push, workflow_dispatch]

jobs:

  binary-sign:
    runs-on: windows-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Copy binary to workspace
        run: cp c:\\Windows\\notepad.exe ${{ github.workspace }}\\binary.exe

      - name: List files in the repository
        run: |
            ls ${{ github.workspace }}


      - name: Setup SM_CLIENT_CERT_FILE from base64 secret data
        run: |
          echo "${{ secrets.WINDOZE_CERT_DATA }}" | base64 --decode > /d/Certificate_pkcs12.p12
        shell: bash


      - name: Setup Software Trust Manager
        uses: digicert/code-signing-software-trust-action@v1
        with:
              simple-signing-mode: true
              # If the below 2 parameters are supplied, then smctl executable is invoked to attempt the signing.
              input: ${{ github.workspace }}\\binary.exe
              keypair-alias: ${{ secrets.KEYLOCKER_KEYPAIR_ALIAS }}
        env:
              SM_HOST: ${{ secrets.KEYLOCKER_HOST }}
              SM_API_KEY: ${{ secrets.KEYLOCKER_API_KEY }}
              SM_CLIENT_CERT_FILE: D:\\Certificate_pkcs12.p12
              SM_CLIENT_CERT_PASSWORD: ${{ secrets.WINDOZE_CERT_PASSWORD }}
        shell: bash

      - name: upload signed installer
        uses: actions/upload-artifact@v4
        with:
            name: Installer-signed
            path: |
             ${{ github.workspace }}\\binary.exe
             if-no-files-found: error

      - run: echo "This job's status is ${{ job.status }}."

